# Generated by Django 5.2.2 on 2025-08-17 10:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('to_number', models.CharField(db_index=True, max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-received_at',),
            },
        ),
        migrations.CreateModel(
            name='SMSChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_number', models.CharField(db_index=True, max_length=32)),
                ('to_number', models.CharField(db_index=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
