# Generated by Django 5.2.2 on 2025-08-17 10:33

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='category/', verbose_name='Image')),
                ('icon', models.ImageField(blank=True, default=None, null=True, upload_to='category/icons/', verbose_name='Icon')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('priority',),
            },
        ),
    ]
