# Generated by Django 5.2.2 on 2025-09-05 15:27

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=core.fields.WebPImageField(blank=True, default=None, null=True, upload_to='category/icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=core.fields.WebPImageField(blank=True, default=None, null=True, upload_to='category/', verbose_name='Image'),
        ),
    ]
