# Generated by Django 5.2.2 on 2026-01-21 09:12

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_icon_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_crop_applied',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_cropping',
            field=image_cropping.fields.ImageRatioField('icon', '1x1', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='icon cropping'),
        ),
        migrations.AddField(
            model_name='category',
            name='image_crop_applied',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='category',
            name='image_cropping',
            field=image_cropping.fields.ImageRatioField('image', '4x3', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping'),
        ),
    ]
