# Generated by Django 5.2.2 on 2025-08-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to='services/avatars', verbose_name='Avatar')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (TM)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('description_tm', models.TextField(verbose_name='Description (TM)')),
                ('description_ru', models.TextField(verbose_name='Description (RU)')),
                ('description_en', models.TextField(verbose_name='Description (EN)')),
                ('price_min', models.FloatField(blank=True, null=True, verbose_name='Minimum Price')),
                ('price_max', models.FloatField(blank=True, null=True, verbose_name='Maximum Price')),
                ('is_catalog', models.BooleanField(default=False, verbose_name='Show in Catalog')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('active_until', models.DateTimeField(blank=True, null=True, verbose_name='Active Until')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('priority', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ServiceAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=100, verbose_name='Attribute Name (TM)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Attribute Name (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Attribute Name (EN)')),
                ('slug', models.SlugField(verbose_name='Attribute Slug')),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('choice', 'Choice')], db_index=True, max_length=20, verbose_name='Input Type')),
                ('is_required', models.BooleanField(default=False, verbose_name='Is Required')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='ServiceAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text_tm', models.TextField(blank=True, null=True, verbose_name='Text Value (TM)')),
                ('value_text_ru', models.TextField(blank=True, null=True, verbose_name='Text Value (RU)')),
                ('value_text_en', models.TextField(blank=True, null=True, verbose_name='Text Value (EN)')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='Number Value')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Boolean Value')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
            },
        ),
        migrations.CreateModel(
            name='ServiceContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=50, verbose_name='Contact Type')),
                ('value', models.CharField(max_length=255, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Service Contact',
                'verbose_name_plural': 'Service Contacts',
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
        migrations.CreateModel(
            name='ServiceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=100, verbose_name='Tag Name (TM)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Tag Name (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Tag Name (EN)')),
            ],
            options={
                'verbose_name': 'Service Tag',
                'verbose_name_plural': 'Service Tags',
            },
        ),
        migrations.CreateModel(
            name='ServiceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Video URL')),
            ],
            options={
                'verbose_name': 'Service Video',
                'verbose_name_plural': 'Service Videos',
            },
        ),
    ]
