# Generated by Django 5.2.2 on 2025-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cities',
            field=models.ManyToManyField(related_name='services', to='regions.city', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='service',
            name='regions',
            field=models.ManyToManyField(related_name='services', to='regions.region', verbose_name='Regions'),
        ),
    ]
