# Generated by Django 5.2.2 on 2025-08-19 18:39

import apps.services.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_cities_service_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceimage',
            name='url',
        ),
        migrations.RemoveField(
            model_name='servicevideo',
            name='url',
        ),
        migrations.AddField(
            model_name='service',
            name='background',
            field=models.ImageField(null=True, upload_to='services/backgrounds', verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(null=True, upload_to='services/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='servicevideo',
            name='file',
            field=models.FileField(null=True, upload_to='services/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'mkv']), apps.services.validators.validate_file_size], verbose_name='Video file'),
        ),
    ]
