# Generated by Django 5.2.2 on 2025-08-26 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_serviceimage_url_remove_servicevideo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name_tm', models.CharField(max_length=100, verbose_name='Name (TM)')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Name (RU)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (EN)')),
                ('icon', models.ImageField(blank=True, help_text='Upload an icon image (SVG/PNG recommended)', null=True, upload_to='contact_type_icons/', verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Contact Type',
                'verbose_name_plural': 'Contact Types',
                'ordering': ['slug'],
            },
        ),
        migrations.RemoveField(
            model_name='servicecontact',
            name='contact_type',
        ),
        migrations.AddField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='servicecontact',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Contact Value'),
        ),
        migrations.AddField(
            model_name='servicecontact',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.contacttype', verbose_name='Contact Type'),
        ),
    ]
