# Generated by Django 5.2.2 on 2025-08-26 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_contacttype_remove_servicecontact_contact_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (TM)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('description_tm', models.TextField(blank=True, null=True, verbose_name='Description (TM)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description (RU)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (EN)')),
                ('price', models.FloatField(verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Product',
                'verbose_name_plural': 'Service Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/product_images', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.serviceproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Service Product Image',
                'verbose_name_plural': 'Service Product Images',
            },
        ),
    ]
