# Generated by Django 5.2.2 on 2025-09-03 09:14

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_favorite_service_alter_review_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=froala_editor.fields.FroalaField(verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=froala_editor.fields.FroalaField(verbose_name='Description (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_tm',
            field=froala_editor.fields.FroalaField(verbose_name='Description (TM)'),
        ),
    ]
