# Generated by Django 5.2.2 on 2025-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproduct',
            name='priority',
            field=models.PositiveIntegerField(default=100, verbose_name='Priority'),
        ),
        migrations.AlterModelOptions(
            name='serviceproduct',
            options={'ordering': ['priority', '-created_at'], 'verbose_name': 'Service Product', 'verbose_name_plural': 'Service Products'},
        ),
    ]

