# Generated by Django 5.2.2 on 2025-09-05 15:41

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_icon_alter_category_image'),
        ('services', '0010_favorite_product_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='icon',
            field=core.fields.WebPImageField(blank=True, help_text='Upload an icon image (SVG/PNG recommended)', null=True, upload_to='contact_type_icons/', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=core.fields.WebPImageField(blank=True, default=None, null=True, upload_to='services/avatars', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='service',
            name='background',
            field=core.fields.WebPImageField(null=True, upload_to='services/backgrounds', verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=core.fields.WebPImageField(null=True, upload_to='services/images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='serviceproductimage',
            name='image',
            field=core.fields.WebPImageField(upload_to='services/product_images', verbose_name='Image'),
        ),
        migrations.RenameModel(
            old_name='ServiceAttribute',
            new_name='Attribute',
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text_tm', models.CharField(max_length=100, verbose_name='Text Value (TM)')),
                ('value_text_ru', models.CharField(max_length=100, verbose_name='Text Value (RU)')),
                ('value_text_en', models.CharField(max_length=100, verbose_name='Text Value (EN)')),
                ('value_number', models.FloatField(blank=True, null=True, verbose_name='Number Value')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Boolean Value')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.attribute', verbose_name='Attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='services.serviceproduct', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Attribute Value',
                'verbose_name_plural': 'Attribute Values',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.DeleteModel(
            name='ServiceAttributeValue',
        ),
    ]
