# Generated by Django 5.2.2 on 2025-09-08 11:04

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_icon_alter_category_image'),
        ('regions', '0001_initial'),
        ('services', '0011_alter_contacttype_icon_alter_service_avatar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cities',
        ),
        migrations.AddField(
            model_name='service',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_cities',
            field=models.ManyToManyField(related_name='services', to='regions.city', verbose_name='Available Cities'),
        ),
        migrations.AddField(
            model_name='service',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regions.city', verbose_name='City'),
        ),
        migrations.CreateModel(
            name='ServiceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, verbose_name='Phone Number')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Service Title')),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact Name')),
                ('description', models.TextField(verbose_name='Service Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='Status')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Admin Note')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Category')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='regions.city', verbose_name='City')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_applications', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Service Application',
                'verbose_name_plural': 'Service Applications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ServiceApplicationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', core.fields.WebPImageField(upload_to='service_applications/images', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.serviceapplication', verbose_name='Application')),
            ],
            options={
                'verbose_name': 'Service Application Image',
                'verbose_name_plural': 'Service Application Images',
                'ordering': ('created_at',),
            },
        ),
    ]
