# Generated by Django 5.2.2 on 2025-09-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_service_cities_service_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_grid_gallery',
            field=models.BooleanField(default=False, verbose_name='Display images as grid'),
        ),
    ]
