# Generated by Django 5.2.2 on 2025-10-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_service_is_grid_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='discount_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Discount Text'),
        ),
    ]
