# Generated by Django 5.2.2 on 2026-01-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_service_discount_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
    ]
