# Generated by Django 5.2.2 on 2026-01-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='Is VIP'),
        ),
    ]
