# Generated by Django 5.2.2 on 2026-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_remove_region_city_name_en'),
        ('services', '0021_service_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='serviceapplication',
            name='city_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='serviceapplication',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='regions.city', verbose_name='City'),
        ),
    ]
