# Generated by ChatGPT
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0024_servicevideo_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicevideo",
            name="hls_playlist",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="HLS playlist path"),
        ),
        migrations.AddField(
            model_name="servicevideo",
            name="hls_ready",
            field=models.BooleanField(default=False, verbose_name="HLS ready"),
        ),
        migrations.AddField(
            model_name="servicevideo",
            name="hls_error",
            field=models.TextField(blank=True, default="", verbose_name="HLS error"),
        ),
        migrations.AddField(
            model_name="servicevideo",
            name="hls_updated_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="HLS updated at"),
        ),
    ]
