# Generated by Django 5.2.2 on 2026-03-05 10:49

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_servicevideo_hls_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicevideo',
            name='preview',
            field=core.fields.WebPImageField(blank=True, null=True, upload_to='services/videos/previews', verbose_name='Preview image'),
        ),
    ]
