# Generated by Django 5.2.2 on 2026-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0027_service_additional_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="work_experience_years",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Work Experience (Years)",
            ),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="work_experience_years",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Work Experience (Years)",
            ),
        ),
    ]
