# Generated by Django 5.2.2 on 2026-03-30 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0028_service_work_experience_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Address"),
        ),
        migrations.AddField(
            model_name="serviceapplication",
            name="price_from",
            field=models.FloatField(blank=True, null=True, verbose_name="Price From"),
        ),
        migrations.CreateModel(
            name="ServiceApplicationLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="services.serviceapplication",
                        verbose_name="Application",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Application Link",
                "verbose_name_plural": "Service Application Links",
                "ordering": ("created_at",),
            },
        ),
    ]
