# Generated by Django 5.2.2 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0029_serviceapplication_address_price_from_and_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="show_location",
            field=models.BooleanField(default=True, verbose_name="Show Location Block"),
        ),
    ]
