# Generated by GPT-5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_service_show_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimage",
            name="position",
            field=models.PositiveIntegerField(default=100, verbose_name="Position"),
        ),
        migrations.AddField(
            model_name="serviceproductimage",
            name="position",
            field=models.PositiveIntegerField(default=100, verbose_name="Position"),
        ),
        migrations.AddField(
            model_name="servicevideo",
            name="position",
            field=models.PositiveIntegerField(default=100, verbose_name="Position"),
        ),
        migrations.AlterModelOptions(
            name="serviceimage",
            options={"ordering": ("position", "id"), "verbose_name": "Service Image", "verbose_name_plural": "Service Images"},
        ),
        migrations.AlterModelOptions(
            name="serviceproductimage",
            options={"ordering": ("position", "id"), "verbose_name": "Service Product Image", "verbose_name_plural": "Service Product Images"},
        ),
        migrations.AlterModelOptions(
            name="servicevideo",
            options={"ordering": ("position", "id"), "verbose_name": "Service Video", "verbose_name_plural": "Service Videos"},
        ),
    ]
