# Generated by Django 5.2.2 on 2026-04-23 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_reviewreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewreport',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports_moderated', to=settings.AUTH_USER_MODEL, verbose_name='Moderator'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='resolution_action',
            field=models.CharField(blank=True, choices=[('remove_content', 'Remove Content'), ('ban_user', 'Ban User'), ('dismiss', 'Dismiss')], default='', max_length=30, verbose_name='Resolution Action'),
        ),
        migrations.AddField(
            model_name='reviewreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At'),
        ),
    ]
