# Generated by Django 5.2.2 on 2026-02-14 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0022_serviceapplication_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Contact Value')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_contacts', to='services.contacttype', verbose_name='Contact Type')),
            ],
            options={
                'verbose_name': 'System Contact',
                'verbose_name_plural': 'System Contacts',
                'ordering': ('priority', 'id'),
            },
        ),
    ]
