# Generated by ChatGPT
from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_account_deletion_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAbout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("about_tm", django_summernote.fields.SummernoteTextField(verbose_name="About (TM)")),
                ("about_ru", django_summernote.fields.SummernoteTextField(verbose_name="About (RU)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "System About",
                "verbose_name_plural": "System About",
                "ordering": ("-updated_at", "-id"),
            },
        ),
    ]
