# Generated by Django 5.2.2 on 2026-03-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_system_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('processed', 'Processed')], default='new', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Client Feedback',
                'verbose_name_plural': 'Client Feedback',
                'ordering': ('-created_at',),
            },
        ),
    ]
