# Generated by Django 5.2.2 on 2026-04-06 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0030_service_show_location"),
        ("system", "0004_clientfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteShowcaseConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                ("limit", models.PositiveSmallIntegerField(default=4, verbose_name="Limit")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Website Showcase",
                "verbose_name_plural": "Website Showcase",
                "ordering": ("-updated_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="WebsiteShowcaseItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=100, verbose_name="Position")),
                ("is_active", models.BooleanField(default=True, verbose_name="Is Active")),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="system.websiteshowcaseconfig",
                        verbose_name="Config",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_showcase_items",
                        to="services.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website Showcase Item",
                "verbose_name_plural": "Website Showcase Items",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="websiteshowcaseitem",
            constraint=models.UniqueConstraint(
                fields=("config", "service"),
                name="website_showcase_config_service_unique",
            ),
        ),
    ]
