# Generated by Django 5.2.2 on 2025-12-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('regions', '0002_city_is_region_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='regions.region', verbose_name='Region'),
        ),
    ]
