# Generated by Django 5.2.2 on 2025-12-09 19:07

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('services', '0013_service_is_grid_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Caption')),
                ('image', core.fields.WebPImageField(upload_to='services/stories', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Starts At')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Story',
                'verbose_name_plural': 'Service Stories',
                'ordering': ('priority', '-starts_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ServiceStoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Viewed At')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to='devices.device', verbose_name='Device')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.servicestory', verbose_name='Story')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service Story View',
                'verbose_name_plural': 'Service Story Views',
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('story', 'user'), name='unique_story_view_per_user'), models.UniqueConstraint(condition=models.Q(('device__isnull', False), ('user__isnull', True)), fields=('story', 'device'), name='unique_story_view_per_device')],
            },
        ),
    ]
