# Generated by Django 5.2.2 on 2025-08-17 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (TM)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ('name_tm',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tm', models.CharField(max_length=255, verbose_name='Name (TM)')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Name (RU)')),
                ('name_en', models.CharField(max_length=255, verbose_name='Name (EN)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ('region', 'name_tm'),
                'unique_together': {('region', 'name_tm')},
            },
        ),
    ]
