# Generated by Django 5.2.2 on 2025-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_region_level',
            field=models.BooleanField(default=False, verbose_name='Is region-level city'),
        ),
    ]
