# Generated by Django 5.2.2 on 2025-12-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('stories_row', 'Stories row'), ('banner_carousel', 'Banner carousel'), ('category_strip', 'Category strip'), ('service_carousel', 'Service carousel'), ('service_list', 'Service list')], max_length=32)),
                ('title_tm', models.CharField(blank=True, default='', max_length=255)),
                ('title_ru', models.CharField(blank=True, default='', max_length=255)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('source_mode', models.CharField(choices=[('manual', 'Manual'), ('query', 'Query')], default='query', max_length=16)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('style', models.JSONField(blank=True, default=dict)),
                ('limit', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Home block',
                'verbose_name_plural': 'Home blocks',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeBlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_items', to='home.homeblock')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Home block item',
                'verbose_name_plural': 'Home block items',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('locale', models.CharField(default='ru', max_length=10)),
                ('platform', models.CharField(default='mobile', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_configs', to='regions.city')),
            ],
            options={
                'verbose_name': 'Home page config',
                'verbose_name_plural': 'Home page configs',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.AddField(
            model_name='homeblock',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='home.homepageconfig'),
        ),
    ]
