# Generated by Django 5.2.2 on 2025-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageconfig',
            name='platform',
        ),
        migrations.AlterField(
            model_name='homepageconfig',
            name='locale',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
