# Generated by Django 5.2.2 on 2025-12-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_homepageconfig_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblock',
            name='source_mode',
            field=models.CharField(choices=[('manual', 'Manual'), ('query', 'Query'), ('pinned_query', 'Pinned + query')], default='query', max_length=16),
        ),
    ]
