# Generated by Django 5.2.2 on 2025-09-05 05:17

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=core.fields.WebPImageField(blank=True, default=None, null=True, upload_to='users/avatars', verbose_name='Avatar'),
        ),
    ]
