# Generated by Django 5.2.2 on 2025-10-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.CreateModel(
            name='UserPhoneHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('assigned_at', models.DateTimeField(verbose_name='Assigned At')),
                ('revoked_at', models.DateTimeField(verbose_name='Revoked At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_history', to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Phone History',
                'verbose_name_plural': 'User Phone History',
                'ordering': ('-revoked_at',),
            },
        ),
    ]
