# Generated by Django 5.2.2 on 2026-04-23 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_deleted_at_and_phone_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModerationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('block', 'Block'), ('unblock', 'Unblock')], max_length=20, verbose_name='Action')),
                ('source', models.CharField(choices=[('app', 'App')], default='app', max_length=20, verbose_name='Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_events_received', to=settings.AUTH_USER_MODEL, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'User Moderation Event',
                'verbose_name_plural': 'User Moderation Events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL, verbose_name='Blocked User')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_created', to=settings.AUTH_USER_MODEL, verbose_name='Blocker')),
            ],
            options={
                'verbose_name': 'User Block',
                'verbose_name_plural': 'User Blocks',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block_pair'), models.CheckConstraint(condition=models.Q(('blocker', models.F('blocked')), _negated=True), name='user_block_no_self_block')],
            },
        ),
    ]
