# Generated by Django 5.2.2 on 2025-09-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tm', models.CharField(max_length=255, verbose_name='Title (TM)')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Title (RU)')),
                ('title_en', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Image')),
                ('link_url', models.CharField(blank=True, help_text='Optional: internal path or external URL', max_length=512, null=True, verbose_name='Link URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Starts At')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ('priority', '-created_at'),
            },
        ),
        migrations.AddField(
            model_name='banner',
            name='cities',
            field=models.ManyToManyField(blank=True, related_name='banners', to='regions.city', verbose_name='Cities'),
        ),
        migrations.AddField(
            model_name='banner',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='banners', to='regions.region', verbose_name='Regions'),
        ),
    ]

