# Generated by Django 5.2.2 on 2025-10-14 05:26

import core.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
        ('services', '0013_service_is_grid_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=core.fields.WebPImageField(upload_to='banners/', verbose_name='Image'),
        ),
    ]
